version: '3'

services:

    mysql:
        image: mysql:8
        container_name: laravel-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: toto
            MYSQL_DATABASE: laravel
            MYSQL_USER: mat
            MYSQL_PASSWORD: toto
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - laravel-net

    web:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
        depends_on:
            - mysql
        networks:
            - laravel-net

networks:
    laravel-net:
        driver: bridge
