version: '3'

services:
    web:
        build:
            context: .
        ports:
            - "8000:9000" # Mappez le port 9000 du conteneur à votre choix (par exemple, 8000 sur l'hôte)
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        ports:
            - "3306:3306"
