name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Validation
      run: |
        
    - name: Tests
      run: |
        
    - name: Build Docker Images
      run: |
        docker build
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker Images
      run: |
        docker push user_management
        
    - name: Deploy to Docker Swarm
      run: |
        ssh -i "VALCKE_M.pem" ec2-user@ec2-35-180-69-168.eu-west-3.compute.amazonaws.com
        ssh -i "VALCKE_M.pem" ec2-user@ec2-35-180-178-112.eu-west-3.compute.amazonaws.com
